Feat: Main 페이지 컴포넌트 조립 및 Detail 페이지 캐러셀 완성 Resolves #2, Resolves #5
JISU-Y/etsy-react pull request #6
Opened 2022-02-10 05:49 UTC by JISU-Y

Refactor
- 공용 컴포넌트 피드백 수정

Feat
- swr Data fetching
- Main 페이지 컴포넌트 조립
- Detail 페이지 routing
- Detail 페이지 캐러셀 (Swiper) 적용

2022-02-10 14:43 UTC, addiescode-sj requested changes
지수님~ PR 사이즈가 조금 커서, 일단 눈에 보이는 부분들은 다 코멘트드리려고 했는데 제가 놓친게 있을 수 있으니 지금 리뷰해 드리는 것 반영하고 리뷰 다시 걸어주시면 더 확인해드리겠습니다.

swr fetching hook 관련해서는 컨셉에 대한 이해와 더불어 -> 그래서 실제 코드에서는 어떻게 활용하면 좋을지까지의 연결이 필요해보여서, 따로 중점적으로 정리해 노션 문서로 공유해드려볼게요.

수고 많으셨습니다!

2022-02-10 14:43 UTC, addiescode-sj commented on src/components/Favorite.tsx
> +interface FavoriteProps {
보통 이런 interface의 Props이름은 export해줄 필요가 없고 해당 컴포넌트 안에서만 쓰인다면, 간단하게 Props라고 네이밍해주는 편입니다. 혹은 인터페이스라는 것을 나타내는 이니셜인 I를 붙여 IFavorite라고 구분해 써주기도합니다 :)

2022-02-10 14:43 UTC, addiescode-sj commented on src/components/Favorite.tsx
> +    <Heart {...{ size }}>
`size={size} ` 로 들어갔어야할것같네요!

2022-02-10 14:43 UTC, addiescode-sj commented on src/components/Footer.tsx
> +    <FooterContainer>
Footer jsx파일과 styled-components가 한 파일 안에 있어도 전혀 문제가 되는 건 아니지만,
저는 이렇게 한 파일에서 읽어내려야하는 코드라인이 매우 길어지는 경우 비슷한 역할을 하는 코드라인끼리 묶어서 분리하는 것을 선호하는 편입니다.

components 폴더 아래에 Footer라는 파일 디렉토리를 하나 만들고, 해당 파일 디렉토리 하위에 
Footer.tsx와 Footer.style.ts, index.ts 세개의 파일을 생성해 

Footer.tsx -> tsx파일, + styled-components를 import해서 사용한다.
Footer.style.ts -> styled-components 파일
index.ts -> Footer.tsx를 default로 import해주는 진입용 파일

이렇게 세개로 역할을 구분해 생성해주는 습관을 들여보면 어떨까요? 😊

2022-02-10 14:43 UTC, addiescode-sj commented on src/components/Footer.tsx
> +            (el: { title: string; contents: string; extra?: string }) => (
해당 라인 destruction을 활용하지 않으신 것 같아요.
우선 아래와 같이 el로 별칭 붙여준 것은 없애주셔도 됩니다.

```jsx
{aboutList.map(
            ({ title: string; contents: string; extra?: string }) => ( 
```

그리고, destruction 한걸 활용하는 부분에서는 이렇게 활용해주시면 됩니다.

```jsx
 <div key={title}>
   <h2>{title}</h2>
        <p>
             {contents}
             {extra && <span>{extra}</span>}
         </p>
 </div>
```

2022-02-10 14:43 UTC, addiescode-sj commented on src/components/Footer.tsx
> +
음 혹시 prettier 적용이 안되어있나요~? 
컴포넌트를 작성하는 코드들에서는 일부러 띄어쓰기를 하지 않으셔도 됩니다.

2022-02-10 14:43 UTC, addiescode-sj commented on src/components/Footer.tsx
> +  & > div {
이렇게 깊게 nesting 되어있는 경우는 styled-component들을 좀 더 명시적인 목적으로 활용하면서 가능한 잘게 쪼개서 나타냈으면 좋겠어요! 쪼개면 가독성, 유지보수 측면에서도 활용도가 좋고요.

리액트 컴포넌트를 일부러 잘게 쪼개는 목적과 비슷한 문맥이라고 이해하시면 좋습니다. 

About안에 역할이 딱 보이는 (명시적인) UI가 아니라 단순히 영역을 구분하기 위해 div엘리먼트를 사용한건데, 이때 위계를 나타내는 데 조금 어려움이 있으시다면 `AboutContainer` -> `AbountWrapper` -> `AboutBox` ... 순으로 나타내는걸 추천드립니다 :)

2022-02-10 14:43 UTC, addiescode-sj commented on src/components/Footer.tsx
> +  button {
이런 button, h3도 다 하나의 styled-component로 분리해주세요!

2022-02-10 14:43 UTC, addiescode-sj commented on src/components/Footer.tsx
> +  h4 {
여기서부터도 위에서 말씀드린 리뷰 적용해주시면 될 것 같습니다.
전체적으로 styled-components를 명시적인 의도로 (해당 UI의 역할과 기능을 코드에서 알려주는 역할) 활용했으면 좋겠어요!

2022-02-10 14:43 UTC, addiescode-sj commented on src/components/Header.tsx
> +interface Props {}
나중에 추가될거라서 빈 Props로 놔두신건가요~? 
활용하지 않는다면 여기서도, function Header에서 타입을 명시한곳에서도 없애주시면 됩니다.

2022-02-10 14:43 UTC, addiescode-sj commented on src/components/Header.tsx
> +        {menu.map((tab: string) => (
tab은 menu에 의해 이미 string으로 추론되어있는 상황이기때문에 타입을 명시하지않으셔도 됩니다 :)

2022-02-10 14:43 UTC, addiescode-sj commented on src/components/TabMenu.tsx
> +    <MenuContainer {...{ list, currentTab }}>
여기서는 굳이 destruction이 필요가 없지않을까요? 
list={list} currentTab={currentTab} 으로 바로 넣어주는게 더 좋아보여요.

2022-02-10 14:43 UTC, addiescode-sj commented on src/hooks/useMainData.ts
> +// swr custom hook으로 만드는 부분은 너무 모르겠습니다..
이 부분, swr을 한꺼번에 호출하는 custom hook으로 만들어 연관된 데이터를 다 fetch하고 return문 안에 포함하신것 자체는 잘 하셨습니다. 다만 swr의 컨셉과 이런 역할을 하는 hook의 위치가 어디 있으면 좋을지에 대해서는, 따로 중점적으로 다루고 이번주 페어프로그래밍 시간에 리뷰해드리는게 더 좋겠네요. :) 

제가 이 부분에 대해서는 자세히 문서로 만들어 저희 프로젝트 링크에 공유해놓을게요~

2022-02-10 14:43 UTC, addiescode-sj commented on src/pages/Detail/Detail.tsx
> +import React from 'react';
`import React, { useEffect } from 'react';`

하고 아래라인에서는 React.useEffect가 아니라 useEffect로 쓰시면 됩니다!

2022-02-10 14:43 UTC, addiescode-sj commented on src/pages/Detail/Detail.tsx
> +  if (!data) return <div>...loading</div>;
[React Suspense
](https://reactjs.org/docs/concurrent-mode-suspense.html)
Experimental이라 프로덕트에 쓰진 못하지만, 
이 라인을 리액트 18버전에서는 어떻게 쓰면 효율적인지 알기 위해 공부할겸 읽어 보셔도 좋을 것 같아요!

React 18에서 안정화될 예정이라, 면접때 꺼낼 얘기로도 좋을 것 같고요.
하지만 여기 적용하기보다는 그냥 공부하는 차원에서 한번  읽어보셨으면합니다 :)

2022-02-10 14:43 UTC, addiescode-sj commented on src/pages/Detail/components/ImageSection.tsx
> +const MainSwiperSettings = {
타입이 아닌데 파스칼케이스네요! 캐피털바꿔주세요 ㅎㅎ

2022-02-10 14:43 UTC, addiescode-sj commented on src/pages/Main/Main.tsx
> +  const [currentTab, setCurrentTab] = React.useState(0);
swr는 필요할때 언제든 호출해서 쓸수 있는 컨셉이기때문에 굳이 state로 다시 넣어주실 필요는 없을 것 같아요.
앞에서 리뷰드렸던것처럼 swr컨셉+ 코드 안에서 활용하는 방법 등을 제가 따로 중정적으로 다뤄서 정리해드려볼게요 :)

2022-02-10 14:43 UTC, addiescode-sj commented on src/pages/Main/components/Card.tsx
> +            {[1, 2, 3, 4, 5].map(el => (
으음 이렇게 컴포넌트가 렌더되는 코드에서 바로 Array를 만들어서 map돌려주는것보다는 이런식으로 shallow-copy된 배열을 만들어서 그 안에서 처리해주는게 좋아보여요. length를 넣어서 쓰셔도되고, 원소 하나하나를 만들고싶다면 만들고싶은 array를 넣어주셔도 되고요. 

[mdn 참고
](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from)

```js

Array.from({length:5}, n => ...)
Array.from([1, 2, 3, 4, 5], n => ...)

```

2022-02-11 04:24 UTC, JISU-Y commented on src/components/Footer.tsx
> +            (el: { title: string; contents: string; extra?: string }) => (
`
{aboutList.map(
            ({ title: string; contents: string; extra?: string }) => ( 
`
이렇게 했는데 동작하지 않아서 따로 찾아보았습니다!

`
onTextBoxInit({ element }: {element: ElementRef }){} 
`

이런식으로 하라고 하는데 깔끔해보이지 않는 것 같아서 어떻게 해야할 지 모르겠습니다 😥

2022-02-11 04:27 UTC, JISU-Y commented on src/pages/Main/Main.tsx
> +  const [currentTab, setCurrentTab] = React.useState(0);
제가 swr로 가져온 배열 data를 filter 사용해서 가공하려고 했는데, filter 함수를 render문 밖으로 빼려고 하다보니 이렇게 하게 되었습니다..! 

filter함수가 return문 안에 있어도 상관 없나요? 혹시 filtering 하는 다른 패턴?이 있는 것인지 궁금합니다.!

2022-02-12 03:13 UTC, addiescode-sj commented on src/components/Footer.tsx
> +            (el: { title: string; contents: string; extra?: string }) => (
에고, 비구조화 할당만 하면 되는데, 타입을 다시 선언해주셔서 에러가 나는걸거예요. 

제가 el로 별칭 붙인것만 언급하고 그대로 복사해서 썼네요 😅
이렇게 바꿔보실래요?

```ts
{aboutList.map(({ title, contents,  extra }) => ())
```

2022-02-13 01:32 UTC, merged